version: '3.8'

services:
  fe-server:
    image: thaily/fe-server:latest
    container_name: fe-server
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - lvtn-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lvtn-network:
    external: true
